import { useState } from "react";
import { Activity, Play, CloudRain, Wind, CheckCircle2, Terminal, Network, Zap, PieChart as PieChartIcon, BarChart2 } from "lucide-react";
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar, Legend } from 'recharts';

// Mock data for graphs
const payoutData = [
  { name: 'Monday', amount: 4500 },
  { name: 'Tuesday', amount: 3200 },
  { name: 'Wednesday', amount: 8900 },
  { name: 'Thursday', amount: 2100 },
  { name: 'Friday', amount: 5600 },
  { name: 'Saturday', amount: 12000 },
  { name: 'Sunday', amount: 3400 },
];

const claimsData = [
  { name: 'Heavy Rain', count: 120 },
  { name: 'Severe AQI', count: 85 },
  { name: 'Heatwave', count: 40 },
];

export default function Admin() {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);

  const simulateTrigger = async (eventType) => {
    setLoading(true);
    setResult(null);
    try {
      const res = await fetch("http://localhost:4000/api/admin/simulate-trigger", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ zonePincode: "560095", eventType })
      });
      const data = await res.json();
      setResult(data);
    } catch(e) {
      console.error(e);
      alert("Failed to run test trigger.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-6xl mx-auto py-10 font-sans space-y-8">
      
      {/* Header section */}
      <div className="border-b border-slate-800 pb-8 flex items-center justify-between">
        <div>
          <div className="flex items-center text-rose-400 mb-2">
            <Terminal className="w-8 h-8 mr-3 drop-shadow-[0_0_10px_rgba(244,63,94,0.5)]" />
            <h2 className="text-3xl font-extrabold tracking-tight text-white drop-shadow-md">Admin Control Panel</h2>
          </div>
          <p className="text-slate-400 text-sm font-sans mt-2">
             <span className="text-rose-400 font-bold mr-2">Admin Notice:</span> 
             You can manually trigger weather and pollution events for testing purposes below. These will instantly process payouts.
          </p>
        </div>
        <div className="hidden sm:flex px-4 py-2 bg-slate-900 border border-slate-700 rounded-lg shadow-inner items-center">
            <span className="relative flex h-3 w-3 mr-3">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-rose-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-3 w-3 bg-rose-500"></span>
            </span>
            <span className="text-xs font-sans font-bold text-slate-300 uppercase tracking-widest">Admin Mode Active</span>
        </div>
      </div>

      {/* Graphs Section */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="dashboard-card p-6 border border-slate-800 flex flex-col h-96">
          <h3 className="text-white font-bold text-lg mb-6 flex items-center">
            <Activity className="w-5 h-5 mr-2 text-indigo-400" />
            Payout Amounts (Last 7 Days)
          </h3>
          <div className="flex-1 w-full relative">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={payoutData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <defs>
                  <linearGradient id="colorAmount" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#818cf8" stopOpacity={0.8}/>
                    <stop offset="95%" stopColor="#818cf8" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                <XAxis dataKey="name" stroke="#94a3b8" tick={{fontSize: 12}} />
                <YAxis stroke="#94a3b8" tick={{fontSize: 12}} />
                <Tooltip 
                  contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155', borderRadius: '8px', color: '#fff' }}
                  itemStyle={{ color: '#818cf8' }}
                />
                <Area type="monotone" dataKey="amount" stroke="#818cf8" strokeWidth={3} fillOpacity={1} fill="url(#colorAmount)" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="dashboard-card p-6 border border-slate-800 flex flex-col h-96">
          <h3 className="text-white font-bold text-lg mb-6 flex items-center">
            <BarChart2 className="w-5 h-5 mr-2 text-emerald-400" />
            Claims Generated By Trigger Type
          </h3>
          <div className="flex-1 w-full relative">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={claimsData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false} />
                <XAxis dataKey="name" stroke="#94a3b8" tick={{fontSize: 12}} />
                <YAxis stroke="#94a3b8" tick={{fontSize: 12}} />
                <Tooltip 
                  cursor={{fill: '#334155', opacity: 0.4}}
                  contentStyle={{ backgroundColor: '#1e293b', borderColor: '#334155', borderRadius: '8px', color: '#fff' }}
                  itemStyle={{ color: '#34d399' }}
                />
                <Bar dataKey="count" fill="#34d399" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Trigger Controls */}
      <h3 className="text-white font-bold text-xl mt-12 mb-4">Manual Test Triggers</h3>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="dashboard-card p-6 flex flex-col relative group border border-slate-800 hover:border-cyan-500/50 transition-colors overflow-hidden">
          <div className="absolute top-0 right-0 w-32 h-32 bg-cyan-500/10 blur-2xl rounded-full pointer-events-none group-hover:bg-cyan-500/20 transition-colors"></div>
          
          <div className="flex items-center mb-6 z-10">
            <div className="w-12 h-12 bg-slate-900 border border-slate-700 rounded-lg flex items-center justify-center mr-4 shadow-inner">
              <CloudRain className="w-6 h-6 text-cyan-400" />
            </div>
            <div>
               <h3 className="font-bold text-lg text-white mb-1 tracking-wide">Trigger: Heavy Rain</h3>
               <span className="text-[10px] font-sans font-bold text-cyan-400 uppercase tracking-widest bg-cyan-500/10 px-2 py-0.5 rounded border border-cyan-500/20">Condition: &gt;35mm/hr</span>
            </div>
          </div>
          
          <p className="text-sm font-sans text-slate-400 mb-8 flex-grow z-10 border-l-2 border-slate-700 pl-3">
             Manually simulates extreme rainfall in Pincode 560095. This will automatically process payouts for all active workers in this area.
          </p>
          
          <button disabled={loading} onClick={() => simulateTrigger("HEAVY_RAIN")} 
             className="w-full bg-slate-800 hover:bg-slate-700 text-cyan-300 border border-cyan-500/30 flex items-center justify-center py-3 rounded-lg text-sm font-sans font-bold shadow-[0_0_15px_rgba(6,182,212,0.15)] group-hover:shadow-[0_0_20px_rgba(6,182,212,0.3)] transition-all disabled:opacity-50 z-10 uppercase tracking-widest">
             <Play className="w-4 h-4 mr-2"/> Run Simulation
          </button>
        </div>

        <div className="dashboard-card p-6 flex flex-col relative group border border-slate-800 hover:border-amber-500/50 transition-colors overflow-hidden">
          <div className="absolute top-0 left-0 w-32 h-32 bg-amber-500/10 blur-2xl rounded-full pointer-events-none group-hover:bg-amber-500/20 transition-colors"></div>
          
          <div className="flex items-center mb-6 z-10">
            <div className="w-12 h-12 bg-slate-900 border border-slate-700 rounded-lg flex items-center justify-center mr-4 shadow-inner">
              <Wind className="w-6 h-6 text-amber-500" />
            </div>
            <div>
               <h3 className="font-bold text-lg text-white mb-1 tracking-wide">Trigger: Severe Air Pollution</h3>
               <span className="text-[10px] font-sans font-bold text-amber-500 uppercase tracking-widest bg-amber-500/10 px-2 py-0.5 rounded border border-amber-500/20">Condition: AQI &gt; 350</span>
            </div>
          </div>
          
          <p className="text-sm font-sans text-slate-400 mb-8 flex-grow z-10 border-l-2 border-slate-700 pl-3">
             Manually simulates hazardous air quality in Pincode 560095. Prompts automatic payouts for workers operating under these dangerous conditions.
          </p>
          
          <button disabled={loading} onClick={() => simulateTrigger("SEVERE_AQI")} 
             className="w-full bg-slate-800 hover:bg-slate-700 text-amber-400 border border-amber-500/30 flex items-center justify-center py-3 rounded-lg text-sm font-sans font-bold shadow-[0_0_15px_rgba(245,158,11,0.15)] group-hover:shadow-[0_0_20px_rgba(245,158,11,0.3)] transition-all disabled:opacity-50 z-10 uppercase tracking-widest">
             <Play className="w-4 h-4 mr-2"/> Run Simulation
          </button>
        </div>
      </div>

      {result && (
        <div className="mt-8 p-6 bg-slate-900 rounded-xl shadow-[0_0_30px_rgba(0,0,0,0.5)] border border-slate-700 text-white animate-in slide-in-from-bottom-5">
          <h3 className="font-bold text-emerald-400 flex items-center text-sm mb-6 uppercase tracking-widest font-sans">
            <Zap className="w-5 h-5 mr-3 text-emerald-400 drop-shadow-[0_0_5px_rgba(52,211,153,0.8)]" />
            SUCCESS: {result.message}
          </h3>
          <div className="grid grid-cols-2 gap-6 relative">
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 w-[1px] h-3/4 bg-slate-800"></div>
            
            <div className="flex flex-col items-center justify-center py-4">
               <p className="text-slate-500 text-xs font-sans font-semibold uppercase tracking-widest mb-2 flex items-center">
                 <Network className="w-4 h-4 mr-2"/> Accounts Processed
               </p>
               <p className="text-5xl font-extrabold text-white drop-shadow-md">{result.claimsAutoGenerated}</p>
            </div>
            
            <div className="flex flex-col items-center justify-center py-4">
               <p className="text-slate-500 text-xs font-sans font-semibold uppercase tracking-widest mb-2 flex items-center">
                 <Activity className="w-4 h-4 mr-2"/> Total Money Disbursed
               </p>
               <p className="text-5xl font-extrabold text-emerald-400 drop-shadow-[0_0_10px_rgba(16,185,129,0.3)]">₹{result.totalPayoutFired}</p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
