package com.gigshield.api.controllers;

import com.gigshield.api.models.Claim;
import com.gigshield.api.models.Policy;
import com.gigshield.api.models.Worker;
import com.gigshield.api.repositories.ClaimRepository;
import com.gigshield.api.repositories.PolicyRepository;
import com.gigshield.api.repositories.WorkerRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/api/admin")
public class AdminController {

    @Autowired
    private WorkerRepository workerRepository;

    @Autowired
    private PolicyRepository policyRepository;

    @Autowired
    private ClaimRepository claimRepository;

    @PostMapping("/simulate-trigger")
    public ResponseEntity<?> simulateTrigger(@RequestBody Map<String, String> payload) {
        try {
            String zonePincode = payload.get("zonePincode");
            String eventType = payload.get("eventType");

            List<Worker> allWorkers = workerRepository.findAll();
            List<String> workersInZone = allWorkers.stream()
                    .filter(w -> zonePincode.equals(w.getZonePincode()))
                    .map(Worker::getId)
                    .collect(Collectors.toList());

            if (workersInZone.isEmpty()) {
                return ResponseEntity.ok("{\"message\": \"Trigger fired, but no workers in this zone.\"}");
            }

            List<Policy> allPolicies = policyRepository.findByStatus("ACTIVE");
            List<Policy> targetPolicies = allPolicies.stream()
                    .filter(p -> workersInZone.contains(p.getWorkerId()))
                    .collect(Collectors.toList());

            if (targetPolicies.isEmpty()) {
                return ResponseEntity.ok("{\"message\": \"Trigger fired, no active policies found.\"}");
            }

            List<Claim> claims = new ArrayList<>();
            double totalPayout = 0;

            for (Policy policy : targetPolicies) {
                double payout = policy.getMaxPayout() * ("HEAVY_RAIN".equals(eventType) || "SEVERE_AQI".equals(eventType) || "FLASH_FLOOD".equals(eventType) ? 1.0 : 0.5);

                Claim claim = new Claim();
                claim.setPolicyId(policy.getId());
                claim.setTriggerEvent(eventType);
                claim.setPayoutAmount(payout);
                claim.setStatus("APPROVED");
                
                Claim savedClaim = claimRepository.save(claim);
                claims.add(savedClaim);
                totalPayout += payout;

                policy.setStatus("CLAIMED");
                policyRepository.save(policy);
            }

            Map<String, Object> response = new HashMap<>();
            response.put("message", "Trigger " + eventType + " fired successfully.");
            response.put("claimsAutoGenerated", claims.size());
            response.put("totalPayoutFired", totalPayout);

            return ResponseEntity.ok(response);
        } catch (Exception e) {
            return ResponseEntity.internalServerError().body("{\"error\": \"Internal Server Error\"}");
        }
    }
}
